#include "character.hpp"

Skeleton::Skeleton()
{
    this->loadImage(State::Idle, CFG_SKELETON_IMG_IDLE_PATH, CFG_SKELETON_IMG_IDLE_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME);
    this->loadImage(State::Attack, CFG_SKELETON_IMG_ATTACK_PATH, CFG_SKELETON_IMG_ATTACK_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME);
    this->loadImage(State::Dead, CFG_SKELETON_IMG_DEAD_PATH, CFG_SKELETON_IMG_DEAD_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME);
    this->loadImage(State::Hit, CFG_SKELETON_IMG_HIT_PATH, CFG_SKELETON_IMG_HIT_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME);
    this->loadImage(State::Walk, CFG_SKELETON_IMG_WALK_PATH, CFG_SKELETON_IMG_WALK_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME);
    this->loadImage(State::Jump, CFG_SKELETON_IMG_JUMP_PATH, CFG_SKELETON_IMG_JUMP_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME * 3);
    this->attack = CFG_SKELETON_STAT_ATTACK;
    this->defend = CFG_SKELETON_STAT_DEFEND;
    this->health = CFG_SKELETON_STAT_HEALTH;
    this->scale = CFG_SKELETON_IMG_SCALE;
    this->setState(State::Idle);
}
Skeleton::~Skeleton(){};
