#include "character.hpp"

Skeleton::Skeleton()
{
    this->loadImage(ImageState::Idle, CFG_SKELETON_IMG_IDLE_PATH, CFG_SKELETON_IMG_IDLE_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME);
    this->loadImage(ImageState::Attack, CFG_SKELETON_IMG_ATTACK_PATH, CFG_SKELETON_IMG_ATTACK_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME);
    this->loadImage(ImageState::Dead, CFG_SKELETON_IMG_DEAD_PATH, CFG_SKELETON_IMG_DEAD_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME);
    this->loadImage(ImageState::Hit, CFG_SKELETON_IMG_HIT_PATH, CFG_SKELETON_IMG_HIT_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME);
    this->loadImage(ImageState::Walk, CFG_SKELETON_IMG_WALK_PATH, CFG_SKELETON_IMG_WALK_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME);
    this->loadImage(ImageState::Jump, CFG_SKELETON_IMG_JUMP_PATH, CFG_SKELETON_IMG_JUMP_FRAMES, CFG_SKELETON_IMG_SWITCH_TIME * 3);
    this->attack = CFG_SKELETON_STAT_ATTACK;
    this->defend = CFG_SKELETON_STAT_DEFEND;
    this->health = CFG_SKELETON_STAT_HEALTH;
    this->scale = CFG_SKELETON_IMG_SCALE;
    this->setState(ImageState::Idle);
}
Skeleton::~Skeleton(){};
