#include "character.hpp"

Warrior::Warrior()
{
    this->loadImage(State::Idle, CFG_WARRIOR_IMG_IDLE_PATH, CFG_WARRIOR_IMG_IDLE_FRAMES, CFG_WARRIOR_IMG_SWITCH_TIME);
    this->loadImage(State::Attack, CFG_WARRIOR_IMG_ATTACK_PATH, CFG_WARRIOR_IMG_ATTACK_FRAMES, CFG_WARRIOR_IMG_SWITCH_TIME);
    this->loadImage(State::Dead, CFG_WARRIOR_IMG_DEAD_PATH, CFG_WARRIOR_IMG_DEAD_FRAMES, CFG_WARRIOR_IMG_SWITCH_TIME);
    this->loadImage(State::Hit, CFG_WARRIOR_IMG_HIT_PATH, CFG_WARRIOR_IMG_HIT_FRAMES, CFG_WARRIOR_IMG_SWITCH_TIME);
    this->loadImage(State::Walk, CFG_WARRIOR_IMG_WALK_PATH, CFG_WARRIOR_IMG_WALK_FRAMES, CFG_WARRIOR_IMG_SWITCH_TIME);
    this->loadImage(State::Jump, CFG_WARRIOR_IMG_JUMP_PATH, CFG_WARRIOR_IMG_JUMP_FRAMES, CFG_WARRIOR_IMG_SWITCH_TIME * 3);
    this->attack = CFG_WARRIOR_STAT_ATTACK;
    this->defend = CFG_WARRIOR_STAT_DEFEND;
    this->health = CFG_WARRIOR_STAT_HEALTH;
    this->scale = CFG_WARRIOR_IMG_SCALE;
    this->setState(State::Idle);
}
Warrior::~Warrior(){};
